### ISSUE TITLE
Make pdf link appear

### ISSUE THREAD

**Issue by michaelgfalk** [wikihistories/reports#4]
In the YAML header for 2024.qmd, this isn't working:

```
format-links: 
  - text: PDF
    href: 2024.pdf
    icon: file-pdf
```

Find a solution!
